l_english:

WPS:0 "Warhawk Private Security Focus Tree"

### Names ###

########################################
### Character Localization - Leaders ###
########################################
WPS_max_payne: "Max Payne"

####################################
### Events - Warhawk Private Security ###
####################################

#####################################################
### National Focus Localisation ###
#####################################################
